### ISSUE TITLE
Component_VersionTypescript

### ISSUE THREAD

**Issue by ticoraph** [Mohrpheus78/Citrix#2]
hello,
If TEAMS is optimized, what is the value in Component_VersionTypescript?

I test this command on my VDI but nothing in the value : 
`Get-WmiObject -Namespace root\citrix\hdx -Class Citrix_VirtualChannel_Webrtc_Enum | Select-Object -ExpandProperty Component_VersionTypescript`

Thanks!

**Comment by Mohrpheus78** [comment]
Please check Readme. You have to create a special registry value first.
